# for i in range(12):
#     if(i == 5):
#         print("leave the loop")
#         break
#     print("5 *" , i, "=", 5 * i)

# for i in range(9):
#     if(i == 5):
#         print("skip the iteration")
#         continue
#     print("5 *" , i, "=", 5 * i)


# for i in range(1,101,1):
#     print(i ,end=" ")
#     if(i==10):
#         break
#     else:
#         print("Mississippi")
# print("Thank you")


for i in [2,3,4,6,8,0]:
    if (i%2==0):
        continue
    print(i)