# # import math

# # result = math.sqrt(9)
# # print(result)  # Output: 3.0


# # from math import sqrt

# # result = sqrt(9)
# # print(result)  # Output: 3.0

# # import math
# # print(math.sqrt(16))

# # from math import sqrt,pi
# # result = sqrt(25)
# # print(result)
# # print(pi)

# from math import *
# resul = sqrt(16)
# print(resul)
# print(pi)

# import math as we
# print(we.sqrt(36))
# print(we.pi)

# import math
# print(dir(math))

import math
result = math.sqrt(4)
print(result)
from math import sqrt
real = sqrt(36)
print(real)